### ISSUE TITLE
Shift/Esprima booth?

### ISSUE THREAD

**Issue by jsoverson** [jQuerySF/Open-Source-Bazaar-2015#13]
It would be great if we could have a booth focusing on parsing and manipulating JavaScript with Shift or Esprima.

cc @ariya @michaelficarra

**Comment by TheAlphaNerd** [comment]
@jsoverson can you email me (you can find it in my profile) 

I'll send you the details needed to officially sign up

**Comment by TheAlphaNerd** [comment]
all set up
