### ISSUE TITLE
Appium

### ISSUE THREAD

**Issue by Jonahss** [jQuerySF/Open-Source-Bazaar-2015#2]
[appium](appium.io) would be happy to have a booth. We want to do something creative and invite our community members to join us at the conference!

We were thinking of some interactive demos, perhaps a jukebox powered by mobile devices!

- www.github.com/appium/appium
- http://discuss.appium.io

**Comment by TheAlphaNerd** [comment]
This would be awesome!!! Will follow up with more details soon.

**Comment by TheAlphaNerd** [comment]
See you there :P
