### ISSUE TITLE
Drywall

### ISSUE THREAD

**Issue by jedireza** [jQuerySF/Open-Source-Bazaar-2015#3]
I'd be thrilled to spread the word about [Drywall](https://github.com/jedireza/drywall). I know I told you this weekend, but I think this is a great idea for booths!

**Comment by TheAlphaNerd** [comment]
This project is awesome! I'll follow up with more details in the next week!!!

**Comment by TheAlphaNerd** [comment]
sorry you won't be able to make it

**Comment by jedireza** [comment]
Me too. I love the idea of an open source bazaar.
