### ISSUE TITLE
Sentry

### ISSUE THREAD

**Issue by dcramer** [jQuerySF/Open-Source-Bazaar-2015#4]
Sentry is an error logging application. We have some pretty kickass JavaScript tooling as well (and more coming!):

https://github.com/getsentry

Not entirely sure if it fits what you have in mind for the program, but figured we'd throw our hat into the ring either way.

Given the unfair assumption that no one knows what Sentry is, we're a for-profit business but we keep everything free and open for the product. We'd also just pay as we generally like giving back to the community :)

**Comment by TheAlphaNerd** [comment]
Email incoming :D

**Comment by TheAlphaNerd** [comment]
See you soon!!!
