### ISSUE TITLE
The jQuery.X Project

### ISSUE THREAD

**Issue by joshualjohnson** [jQuerySF/Open-Source-Bazaar-2015#5]
Bringing MVVM directly to your jQuery projects

https://github.com/jljlabs/jquery.x

This is a small framework I started, not to long ago, that is similar to Angular, but provides you with hooks for updating DOM directly in the apply loop. Each object (x, controller, view, & the apply loop) is extensible and provides you with the ability to easily extend the framework. In X, the Controller is an object, rather than a function, which allows you to move your business logic out of the View Model object. The framework also supports Aspects (our own version of directives). Did I mention that the digest loop has been removed, as well as the complexity of Angular?

It is my belief that other jQuery type developers could more easily pick up on the concepts in jQuery.x than in AngularJS.

**Comment by TheAlphaNerd** [comment]
Hey Josh,

Thank you so much for submitting your project. We'll be following up soon with more information about the event.

**Comment by TheAlphaNerd** [comment]
@joshualjohnson 

Can you tell me a bit more about your project and the people who are currently using it?
