### ISSUE TITLE
WET-BOEW (Web Experience Toolkit)

### ISSUE THREAD

**Issue by ElismaD** [jQuerySF/Open-Source-Bazaar-2015#7]
I would love to submit the [Web Experience Toolkit (WET)](https://github.com/wet-boew/wet-boew). An open source code library (30+ plugins, 5+ polyfills, 5+ study cases and tools, 5+ themes) for building innovative websites that are accessible, usable, interoperable, mobile-friendly and multilingual. We, at the Government of Canada, led this collaborative open source project for the past four years, with the private sector, open source community and the open government.

**Comment by TheAlphaNerd** [comment]
This looks amazing! @ElismaD would you be able to come as a representative?

**Comment by ElismaD** [comment]
That's the plan, just need to clear some permissions at work and that could be possible. Only thing is I dunno if I can volunteer if I man the booth.

**Comment by TheAlphaNerd** [comment]
The booth will only be running for two hours a day during lunch. We can find a way to make it all work!

**Comment by ElismaD** [comment]
That sounds really nice. Can you send me the info? And if you can cc my gmail account that would be awesome.

**Comment by TheAlphaNerd** [comment]
invite sent

**Comment by TheAlphaNerd** [comment]
and accepted!
