### ISSUE TITLE
Deku

### ISSUE THREAD

**Issue by lambtron** [jQuerySF/Open-Source-Bazaar-2015#8]
[We](http://www.github.com/segmentio) are interested in having a booth/doing a talk on [Deku](https://github.com/dekujs/deku).

This was released recently (within the past month). More information here:
- https://segment.com/blog/deku-our-functional-alternative-to-react/
- https://github.com/stevenmiller888/awesome-deku (deku related goodies)

Let us know! Thanks for setting up this great event!

**Comment by TheAlphaNerd** [comment]
Invite sent

**Comment by TheAlphaNerd** [comment]
And accepted!
